from aiogram.dispatcher.filters.state import StatesGroup, State

class UserInfo(StatesGroup):
    # policy = State()
    fio = State()
    telefon = State()
    jins = State()
    age = State()
    education = State()
    prog_language = State()
    additional = State()
    resume = State()
    final = State()
    registered = State()

class CategoryTests(StatesGroup):
    start = State()
    question1 = State()
    question2 = State()
    question3 = State()
    question4 = State()
    question5 = State()
    question6 = State()
    question7 = State()
    question8 = State()
    question9 = State()
    question10 = State()
    question11 = State()
    question12 = State()
    question13 = State()
    question14 = State()
    question15 = State()
    question16 = State()
    question17 = State()
    question18 = State()
    question19 = State()
    question20 = State()